### Find My Profile

GET http://ma.mysuni.sk.com/api/community/profiles
audienceId: r47a-r@ne1-m2-c2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRpdGlvbmFsSW5mb3JtYXRpb24iOnsiY29tcGFueUNvZGUiOiJTS0NDIiwiZW1wbG95ZWVJZCI6IlNLQ0MwOCJ9LCJsb2dpbklkIjoiU0tDQy5TS0NDMDhAc2suY29tIiwidXNlcl9uYW1lIjoiU0tDQy5TS0NDMDhAc2suY29tIiwiZGlzcGxheU5hbWUiOiLqsJXsmqkqKiIsInNjb3BlIjpbImNsaWVudCJdLCJ3b3Jrc3BhY2VzIjp7InN0YXRpb25Xb3Jrc3BhY2VzIjpudWxsLCJzcXVhcmVXb3Jrc3BhY2VzIjpudWxsLCJwYXZpbGlvbldvcmtzcGFjZXMiOm51bGwsImNpbmVyb29tV29ya3NwYWNlcyI6W3siaWQiOiJuZTEtbTItYzIiLCJuYW1lIjoiU0sgVW5pdmVyc2l0eSIsInRlbmFudElkIjoicjQ3YS1yQG5lMS1tMi1jMiIsInJvbGVzIjpbIlVzZXIiXX0seyJpZCI6Im5lMS1tMi1jMTciLCJuYW1lIjoiU0so7KO8KUMmQyIsInRlbmFudElkIjoicjQ3YS1yQG5lMS1tMi1jMTciLCJyb2xlcyI6WyJVc2VyIl19XSwic3R1ZGlvV29ya3NwYWNlIjpudWxsfSwiZXhwIjoxNjA0NzU2ODUxLCJhdXRob3JpdGllcyI6WyJVc2VyIl0sImp0aSI6ImI1YWUyNDlhLTc2NGItNDdlNS04OWExLTY5MmJkYWZhN2JhNiIsImNsaWVudF9pZCI6Im5hcmEifQ.GjHK5NyxdiD2DjXQ8TEnhh-kkhJYSJSpqOxRLuNAAeQ