import { CardCategory } from 'shared/model/CardCategory';
import { CardState } from './CardState';
import { DifficultyLevel } from './DifficultyLevel';
import { GroupBasedAccessRule } from './GroupBasedAccessRule';
import { PermittedCineroom } from './PermittedCineroom';
import { PatronKey } from '@nara.platform/accent';
import CardType from '../shared/model/CardType';
import { PolyglotString } from 'shared/viewmodel/PolyglotString';
import { LangSupport } from './LangSupport';
export interface Card {
  id: string;
  name: PolyglotString;
  type: CardType;
  patronKey: PatronKey;
  thumbImagePath: string;
  thumbnailImagePath: string;
  stampCount: number;
  simpleDescription: PolyglotString;
  difficultyLevel?: DifficultyLevel;
  searchable: boolean;
  tags?: PolyglotString | null;
  categories: CardCategory[];
  permittedCinerooms?: PermittedCineroom[];
  learningTime: number;
  additionalLearningTime: number;
  cardState?: CardState;
  cardStateUpdatedTime: number;
  mainCategory: CardCategory;
  groupBasedAccessRule?: GroupBasedAccessRule;
  langSupports: LangSupport[];
}
