const ExpertListDummy = [
  {
    "result": {
        "total_count": 6,
        "rows": [
            {
                "fields": {
                    "resting": "true",
                    "appointed_date": "2020-01-13 00:00:00",
                    "category_json": "{\"college\": {\"id\": \"CLG00007\",\"name\": \"Leadership\"},   \"channel\": {\"id\": \"CHN0000w\",\"name\": \"Leading Myself\"}}",
                    "college_name": "Leadership",
                    "internal": "true",
                    "id": "IS-009P",
                    "lecture_hour": "1",
                    "channel_id": "CHN0000w",
                    "employee_id": "",
                    "department": "행복비전연구원",
                    "rep_subject_json": "{}",
                    "specialty": "",
                    "channel_name": "Leading Myself",
                    "feedback_id": "",
                    "photo_id": "",
                    "pk": "IS-009P",
                    "tag": "",
                    "tag_uni": "",
                    "college_id": "CLG00007",
                    "introduction_uni": "• 리더십\n• 동기부여\n• 변화관리\n• 셀프 리더십",
                    "lecture_list_id": "",
                    "name": "민승기",
                    "short_introduction": "",
                    "subjects_json": "{\"idNames\":[]}",
                    "career_year": "1",
                    "cineroom_id": "",
                    "introduction": "• 리더십\n• 동기부여\n• 변화관리\n• 셀프 리더십",
                    "jsonParser": "",
                    "career": "• 현 행복비전연구원 원장\n• 전 한국 코카-콜라 보틀링 교육팀장\n• 전 한국능률협회컨설팅 선임 연구원\n• 전 엑스퍼트 컨설팅 전임 교수\n",
                    "email": "",
                    "position": "원장",
                    "department_uni": "행복비전연구원",
                    "name_uni": "민승기",
                    "pavilion_id": "",
                    "lecture_count": "1"
                },
                "sortkey": [
                    "0"
                ],
                "location": {
                    "rowid": 297,
                    "volume": "expert",
                    "table": "expert",
                    "netaddr": "127.0.0.1:7577"
                },
                "copyof": -1
            },
            {
                "fields": {
                    "resting": "true",
                    "appointed_date": "2020-01-13 00:00:00",
                    "category_json": "{\"college\": {\"id\": \"CLG00003\",\"name\": \"행복\"},   \"channel\": {\"id\": \"CHN0000g\",\"name\": \"행복의 이해\"}}",
                    "college_name": "행복",
                    "internal": "false",
                    "id": "IS-00CY",
                    "lecture_hour": "1",
                    "channel_id": "CHN0000g",
                    "employee_id": "",
                    "department": "블룸컴퍼니",
                    "rep_subject_json": "{}",
                    "specialty": "",
                    "channel_name": "행복의 이해",
                    "feedback_id": "",
                    "photo_id": "",
                    "pk": "IS-00CY",
                    "tag": "",
                    "tag_uni": "",
                    "college_id": "CLG00003",
                    "introduction_uni": "• 긍정심리 기반의 조직활성화\n• 긍정 리더십\n• 행복 디자인\n• 심리상담",
                    "lecture_list_id": "",
                    "name": "우보영",
                    "short_introduction": "",
                    "subjects_json": "{\"idNames\":[]}",
                    "career_year": "1",
                    "cineroom_id": "",
                    "introduction": "• 긍정심리 기반의 조직활성화\n• 긍정 리더십\n• 행복 디자인\n• 심리상담",
                    "jsonParser": "",
                    "career": "• 현) 블룸컴퍼니 마스터 마음퍼실리테이터\n• 전) 더 위로 심리연구소 소장\n• 싱가폴 경영대 mbsat티처 코스 중\n• 한국상담학회 전문상담사\n• 한국가족상담협회 가족상담사",
                    "email": "",
                    "position": "퍼실리테이터",
                    "department_uni": "블룸컴퍼니",
                    "name_uni": "우보영",
                    "pavilion_id": "",
                    "lecture_count": "1"
                },
                "sortkey": [
                    "0"
                ],
                "location": {
                    "rowid": 70,
                    "volume": "expert",
                    "table": "expert",
                    "netaddr": "127.0.0.1:7577"
                },
                "copyof": -1
            },
            {
                "fields": {
                    "resting": "true",
                    "appointed_date": "2020-02-03 00:00:00",
                    "category_json": "{\n  \"college\": {\n    \"id\": \"CLG00007\",\n    \"name\": \"Leadership\"\n  },\n  \"channel\": {\n    \"id\": \"CHN0000z\",\n    \"name\": \"Leadership Clinic\"\n  }\n}",
                    "college_name": "Leadership",
                    "internal": "true",
                    "id": "IS-00L0",
                    "lecture_hour": "1",
                    "channel_id": "CHN0000z",
                    "employee_id": "",
                    "department": "mySUNI 전문교수단",
                    "rep_subject_json": "{}",
                    "specialty": "",
                    "channel_name": "Leadership Clinic",
                    "feedback_id": "",
                    "photo_id": "",
                    "pk": "IS-00L0",
                    "tag": "",
                    "tag_uni": "",
                    "college_id": "CLG00007",
                    "introduction_uni": "리더십, 행복, Management",
                    "lecture_list_id": "",
                    "name": "현순엽",
                    "short_introduction": "",
                    "subjects_json": "{\"idNames\":[]}",
                    "career_year": "1",
                    "cineroom_id": "",
                    "introduction": "리더십, 행복, Management",
                    "jsonParser": "",
                    "career": "前 SK하이닉스 기업문화담당\n前 SK이노베이션 기업문화본부장 \n前 SK네트웍스 인력개발실장 \n前 SK텔레콤 Customer기획본부장 ",
                    "email": "sunyeop.hyun@sk.com",
                    "position": "교수",
                    "department_uni": "mySUNI 전문교수단",
                    "name_uni": "현순엽",
                    "pavilion_id": "",
                    "lecture_count": "1"
                },
                "sortkey": [
                    "0"
                ],
                "location": {
                    "rowid": 116,
                    "volume": "expert",
                    "table": "expert",
                    "netaddr": "127.0.0.1:7577"
                },
                "copyof": -1
            },
            {
                "fields": {
                    "resting": "true",
                    "appointed_date": "2020-01-13 00:00:00",
                    "category_json": "{\"college\": {\"id\": \"CLG00007\",\"name\": \"Leadership\"},   \"channel\": {\"id\": \"CHN0000w\",\"name\": \"Leading Myself\"}}",
                    "college_name": "Leadership",
                    "internal": "false",
                    "id": "IS-00BR",
                    "lecture_hour": "1",
                    "channel_id": "CHN0000w",
                    "employee_id": "",
                    "department": "강북삼성병원  ",
                    "rep_subject_json": "{}",
                    "specialty": "",
                    "channel_name": "Leading Myself",
                    "feedback_id": "",
                    "photo_id": "",
                    "pk": "IS-00BR",
                    "tag": "",
                    "tag_uni": "",
                    "college_id": "CLG00007",
                    "introduction_uni": "• 스트레스\n• 소통\n• 공감\n• 감정기억\n• 자기존중감\n• 자존감\n• 중독\n• 가정행복\n• 정신건강\n• 부부",
                    "lecture_list_id": "",
                    "name": "신영철",
                    "short_introduction": "",
                    "subjects_json": "{\"idNames\":[]}",
                    "career_year": "1",
                    "cineroom_id": "",
                    "introduction": "• 스트레스\n• 소통\n• 공감\n• 감정기억\n• 자기존중감\n• 자존감\n• 중독\n• 가정행복\n• 정신건강\n• 부부",
                    "jsonParser": "",
                    "career": "• 강북삼성병원 (교수), 한국중독정신의학회 (이사장)\n• 2011년 문화체육관광부 장관상, 2011년 국민권익위원회위원장 표창\n• 강북삼성병원 기업정신건강연구소 소장, 강북삼성병원 정신겅강의학과\n• 제10대 한국중독정신의학회 이사장\n• 대한불안의학회 홍보이사",
                    "email": "",
                    "position": "교수",
                    "department_uni": "강북삼성병원  ",
                    "name_uni": "신영철",
                    "pavilion_id": "",
                    "lecture_count": "1"
                },
                "sortkey": [
                    "0"
                ],
                "location": {
                    "rowid": 331,
                    "volume": "expert",
                    "table": "expert",
                    "netaddr": "127.0.0.1:7577"
                },
                "copyof": -1
            },
            {
                "fields": {
                    "resting": "true",
                    "appointed_date": "2020-01-13 00:00:00",
                    "category_json": "{\"college\": {\"id\": \"CLG00003\",\"name\": \"행복\"},   \"channel\": {\"id\": \"CHN0000g\",\"name\": \"행복의 이해\"}}",
                    "college_name": "행복",
                    "internal": "false",
                    "id": "IS-00HV",
                    "lecture_hour": "1",
                    "channel_id": "CHN0000g",
                    "employee_id": "",
                    "department": "서울대학교",
                    "rep_subject_json": "{}",
                    "specialty": "",
                    "channel_name": "행복의 이해",
                    "feedback_id": "",
                    "photo_id": "",
                    "pk": "IS-00HV",
                    "tag": "",
                    "tag_uni": "",
                    "college_id": "CLG00003",
                    "introduction_uni": "• 긍정심리학: 행복의 원인, 행복한 사람들의 특징, 행복 증진법에 대한 연구\n'• 사회인지(의사결정): 사회 인지의 전반적인 주제와 선택, 의사결정 연구 ",
                    "lecture_list_id": "",
                    "name": "최인철",
                    "short_introduction": "",
                    "subjects_json": "{\"idNames\":[]}",
                    "career_year": "1",
                    "cineroom_id": "",
                    "introduction": "• 긍정심리학: 행복의 원인, 행복한 사람들의 특징, 행복 증진법에 대한 연구\n'• 사회인지(의사결정): 사회 인지의 전반적인 주제와 선택, 의사결정 연구 ",
                    "jsonParser": "",
                    "career": "-현) 서울대학교 심리학과 교수\n'-현) 서울대학교 행복연구센터 센터장 \n'-전) University of Illinois 조교수",
                    "email": "",
                    "position": "교수",
                    "department_uni": "서울대학교",
                    "name_uni": "최인철",
                    "pavilion_id": "",
                    "lecture_count": "1"
                },
                "sortkey": [
                    "0"
                ],
                "location": {
                    "rowid": 377,
                    "volume": "expert",
                    "table": "expert",
                    "netaddr": "127.0.0.1:7577"
                },
                "copyof": -1
            },
            {
                "fields": {
                    "resting": "true",
                    "appointed_date": "2020-03-24 00:00:00",
                    "category_json": "{\n  \"college\": {\n    \"id\": \"CLG00003\",\n    \"name\": \"행복\"\n  },\n  \"channel\": {\n    \"id\": \"CHN0000g\",\n    \"name\": \"행복의 이해\"\n  }\n}",
                    "college_name": "행복",
                    "internal": "true",
                    "id": "IS-00KL",
                    "lecture_hour": "1",
                    "channel_id": "CHN0000g",
                    "employee_id": "",
                    "department": "SK네트웍스",
                    "rep_subject_json": "{}",
                    "specialty": "",
                    "channel_name": "행복의 이해",
                    "feedback_id": "",
                    "photo_id": "",
                    "pk": "IS-00KL",
                    "tag": "#행복#철학#CEO#특강",
                    "tag_uni": "#행복#철학#CEO#특강",
                    "college_id": "CLG00003",
                    "introduction_uni": "철학으로 보는 행복 이야기",
                    "lecture_list_id": "",
                    "name": "박상규",
                    "short_introduction": "",
                    "subjects_json": "{\"idNames\":[]}",
                    "career_year": "1",
                    "cineroom_id": "",
                    "introduction": "철학으로 보는 행복 이야기",
                    "jsonParser": "",
                    "career": "SK네트웍스 CEO",
                    "email": "parksk@sk.com",
                    "position": "CEO",
                    "department_uni": "SK네트웍스",
                    "name_uni": "박상규",
                    "pavilion_id": "",
                    "lecture_count": "1"
                },
                "sortkey": [
                    "0"
                ],
                "location": {
                    "rowid": 596,
                    "volume": "expert",
                    "table": "expert",
                    "netaddr": "127.0.0.1:7577"
                },
                "copyof": -1
            }
        ]
    },
    "message": "",
    "status": "OK"
}
]

export default ExpertListDummy;