
###
# 동영상 진도율 등록
###
POST http://ma.mysuni.sk.com/api/watch-log-collector/watchLog
Content-Type: application/json

{
"patronKeyString": "r47a@ne1-m2",
"lectureUsid": "LECTURE-CARD-28h",
"start": 1100,
"end": 1110
}

###
# 동영상 진도율 리스트 조회
###
GET http://ma.mysuni.sk.com/api/watch-log-collector/watchLog?patronKeyString=r2y8%40ne1-m2&lectureUsid=LECTURE-CARD-27v


###
# 동영상 시청 총 합계 초 조회
###
GET http://ma.mysuni.sk.com/api/watch-log-collector/watchLog/sumViewSeconds?patronKeyString=r47a@ne1-m2&lectureUsid=LECTURE-CARD-28h


###
# close 버튼 또는 학습완료 시 상태 업데이트 조회
###
POST http://ma.mysuni.sk.com/api/lecture/students/flow/confirm/progressByCardId
Content-Type: application/json
audienceId: r47a-r@ne1-m2-c2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRpdGlvbmFsSW5mb3JtYXRpb24iOnsiY29tcGFueUNvZGUiOiJTS0NDIiwiZW1wbG95ZWVJZCI6IlNLQ0MwOCJ9LCJsb2dpbklkIjoiU0tDQy5TS0NDMDhAc2suY29tIiwidXNlcl9uYW1lIjoiU0tDQy5TS0NDMDhAc2suY29tIiwiZGlzcGxheU5hbWUiOiLqsJXsmqkqKiIsInNjb3BlIjpbImNsaWVudCJdLCJ3b3Jrc3BhY2VzIjp7InN0YXRpb25Xb3Jrc3BhY2VzIjpudWxsLCJzcXVhcmVXb3Jrc3BhY2VzIjpudWxsLCJwYXZpbGlvbldvcmtzcGFjZXMiOm51bGwsImNpbmVyb29tV29ya3NwYWNlcyI6W3siaWQiOiJuZTEtbTItYzIiLCJuYW1lIjoiU0sgVW5pdmVyc2l0eSIsInRlbmFudElkIjoicjQ3YS1yQG5lMS1tMi1jMiIsInJvbGVzIjpbIlVzZXIiXX0seyJpZCI6Im5lMS1tMi1jMTciLCJuYW1lIjoiU0so7KO8KUMmQyIsInRlbmFudElkIjoicjQ3YS1yQG5lMS1tMi1jMTciLCJyb2xlcyI6WyJVc2VyIl19XSwic3R1ZGlvV29ya3NwYWNlIjpudWxsfSwiZXhwIjoxNjA1NTk2Njk0LCJhdXRob3JpdGllcyI6WyJVc2VyIl0sImp0aSI6ImJjMWZmYzMwLTgxYzEtNDcxNC05NmFmLWY3ZjgwYWRkYzk0OCIsImNsaWVudF9pZCI6Im5hcmEifQ.TDYvRK1KYLmyO-jj9a9hqsugmDuaJVsE0eLROK6KrL4

{"denizenKey":{
    "keyString":"r47a-r@ne1-m2-c2","patronType":"Audience"
    },
    "rollBookId":"5a51f4c1-6322-45c5-81b8-139cde8c83e7",
    "name":"강용**",
    "email":"SKCC.SKCC08@sk.com",
    "company":"SK주식회사 C&C",
    "department":"공용계정조직",
    "proposalState":"Approved",
    "programLectureUsid":"",
    "courseLectureUsid":"",
    "leaderEmails":[],
    "url":"",
    "classroomId":"",
    "enClosed":false
    }

# {
#     "denizenKey": {
#         "keyString": "r47a@ne1-m2",
#         "patronType": "Audience"
#     },
#     "rollBookId": "1cd03b20-0c16-4310-b417-42117f2c4227",
#     "name": "박성**",
#     "email": "SKCC.05526@sk.com",
#     "company": "SK주식회사 C&C",
#     "department": "MIS서비스팀",
#     "proposalState": "Approved",
#     "programLectureUsid": "",
#     "courseLectureUsid": "",
#     "enClosed": false,
#     "classroomId": "",
#     "approvalProcess": false,
#     "leaderEmails": [],
#     "url": ""
# }
