apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 6
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: dev03/user:0.0.1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
          - mountPath: /etc/localtime
            name: timezone-config
      volumes:
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
          name: timezone-config
      imagePullSecrets:
      - name: user-secret
  strategy:
    type: RollingUpdate
