apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: dev03/user:0.0.1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: user-secret
  strategy:
    type: RollingUpdate
