apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: user
  namespace: gdi-skuniv-app-ma
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: dev03/user:0.0.1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
#        resources:
#          requests:
#            cpu: "2.5"
#            memory: "5Gi"
#          limits:
#            cpu: "2.5"
#            memory: "5Gi"
        livenessProbe:
          failureThreshold: 20
          httpGet:
            path: /healthCheck
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /healthCheck
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        volumeMounts:
          - name: user-front-persistent-storage
            mountPath: /usr/share/nginx/html/profile
          - name: user-front-persistent-storage
            mountPath: /usr/share/nginx/html/files
          - mountPath: /etc/localtime
            name: timezone-config
      volumes:
        - name: user-front-persistent-storage
          persistentVolumeClaim:
            claimName: nara-pvc-ma
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
          name: timezone-config
      imagePullSecrets:
      - name: harbor-pull-secret
  strategy:
    type: RollingUpdate
