apiVersion: v1
kind: Service
metadata:
  name: user-front-service-next
spec:
  ports:
    - name: '80'
      port: 80
      targetPort: 80
  selector:
    app: user-front-next
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-front-virtualservice-next
spec:
  hosts:
    - 'next.mysuni.sk.com'
  gateways:
    - skuniv-gateway
  http:
    - match:
        - uri:
            prefix: /robots.txt
      route:
        - destination:
            host: user-front-service-next
            port:
              number: 80
    - match:
        - uri:
            exact: /
      #      rewrite:
      #        uri: /suni-main
      route:
        - destination:
            host: user-front-service-next
            port:
              number: 80
    - match:
        - uri:
            prefix: /suni-main
      route:
        - destination:
            host: user-front-service-next
            port:
              number: 80
    - match:
        - uri:
            prefix: /profile
      route:
        - destination:
            host: user-front-service-next
            port:
              number: 80
    - match:
        - uri:
            prefix: /files
      route:
        - destination:
            host: user-front-service-next
            port:
              number: 80
    - match:
        - uri:
            prefix: /manager
      route:
        - destination:
            host: user-front-service-next
            port:
              number: 80
