apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: user
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - skuniv-gateway
  http:
    - match:
        - uri:
            exact: /
#      rewrite:
#        uri: /suni-main
      route:
        - destination:
            host: user-service
            port:
              number: 80
    - match:
        - uri:
            prefix: /suni-main
      route:
        - destination:
            host: user-service
            port:
              number: 80
    - match:
        - uri:
            prefix: /profile
      route:
        - destination:
            host: user-service
            port:
              number: 80
    - match:
        - uri:
            prefix: /file
        route:
          - destination:
              host: user-service
              port:
                number: 80
