export class AplCdoModel {
  title: string = '';
  type: string = '';
  typeName: string = '';
  collegeId: string = '';
  channelId: string = '';
  startDate: number = 0;
  endDate: number = 0;
  institute: string = '';
  requestHour: number = 0;
  requestMinute: number = 0;
  allowHour: number = 0;
  allowMinute: number = 0;
  content: string = '';
  state: string = '';
  fileIds: string = '';
  approvalYn: boolean | undefined;
  approvalId: string = '';
  causeOfReturn: string = '';
}
